Instalar la librería Numpy

In [ ]:
pip install numpy

SyntaxError: invalid syntax (3638225874.py, line 1)

Importar Librerías numpy y pandas


In [2]:
import numpy as np
import pandas as pd

Declarar una variable y asignarle un valor numérico.
Elaborar una estructura de control, utilizando if then.. else if.. else.

In [5]:
prueba = 10
if prueba > 5:
    print("Es mayor a 5")
elif prueba == 5:
    print("Es igual a 5")
else:
    print("Es menor a 5")

print("Prueba es: ",prueba)

Es mayor a 5
Prueba es:  10


Crear una función que devuelva la suma de 3 números enteros.

In [6]:
def funcion_suma(a, b, c):
    return a + b + c

Llamar a la función que suma 3 números enteros.

In [7]:
funcion_suma(1, 2, 3)

6

Llamar a la función que suma 3 números enteros, pero pasar argumentos de tipo "string"

In [8]:
funcion_suma("Prueba", " de", " texto")

'Prueba de texto'

Un inversor financiero está interesado en invertir en la compañía. Se propone comprar durante cada día de la semana 20 acciones. También sabe que la probabilidad de obtener ganancias (aproximadamente 15% en cada inversión) es de 0.56 y la probabilidad de perder el 18% es 0.44 (Solo hay esas dos opciones).
Crear una función llamada retorno_semanal que calcule el valor esperado con la cantidad de acciones compradas cada día, probabilidad de ganancia y no ganancia

In [ ]:
valores= [200, 225, 232, 221, 243, 256, 255]

Crear una variable, asignar valor "None"

In [11]:
var = None

Imprimir la variable cuyo valor es "None"

In [12]:
print(var)

None


Crear un arreglo, con valores de distinto tipo (numérico y texto), luego mostrar el contenido del arreglo.

In [13]:
arreglo = [1, "uno", 2, "dos"];    
print(arreglo)

[1, 'uno', 2, 'dos']


# Numpy
Importar la librería Numpy, con el alias np

In [1]:
import numpy as np

Crear un arreglo con valores numéricos del 0 al 9. Mostrar el contenido del arreglo.

In [2]:
arreglo = np.array([1, 2, 3, 4, 5, 7 ,8 ,9])
print(arreglo)

[1 2 3 4 5 7 8 9]


Crear un arreglo con n-valores numéricos 0. Mostrar el contenido del arreglo.

In [15]:
import random


arreglo_ceros = np.zeros(random.randint(1,10))
print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crear un arreglo con n-valores numéricos 1. Mostrar el contenido del arreglo.

In [17]:
arreglo_unos = np.ones(random.randint(1,10))
print(arreglo_unos)

[1. 1. 1. 1. 1. 1. 1. 1.]


Crear un arreglo con n-valores numéricos, definiendo el número que se va a guardar. Mostrar el contenido del arreglo.

In [21]:
arreglo = np.full(random.randint(1,10), 7)
print(arreglo)

[7 7 7 7 7 7 7]


Crear un arreglo con valores numéricos del 0 al 9 (con arange). Mostrar el contenido del arreglo.

In [49]:
arreglo_valores = np.arange(10)
print(arreglo_valores)

[0 1 2 3 4 5 6 7 8 9]


Crear un arreglo matricial de 2 x 3, con valores numéricos random de 0 .. 9. Mostrar el contenido del arreglo.

In [26]:
arreglo = np.random.randint(10, size=(2, 3))
print(arreglo)

[[0 8 3]
 [1 6 5]]


Crear un arreglo matricial de 2 x 7, con valores numéricos random de 0 .. 99. Mostrar el contenido del arreglo.

In [34]:
matriz = np.random.randint(100, size=(2, 7),dtype=int)
print(matriz)

[[54 15 91 84  8 51 17]
 [49 81  0  7 94 14 24]]


Mostrar la dimensión de la matriz.

In [35]:
print(matriz.ndim)

2


Mostrar la forma de la matriz (cuántas filas y cuántas columnas)

In [31]:
print(matriz.shape)

(2, 7)


Mostrar el tamaño (cantidad de elementos) de la matriz.

In [36]:
print(matriz.size)

14


Mostrar el tipo de elementos de los valores de la matriz.

In [37]:
print(matriz.dtype)

int32


Mostrar el espacio en memoria que ocupa cada elemento de la matriz.

In [38]:
print(matriz.itemsize)

4


Mostrar el tamaño en bytes de la matriz.

In [39]:
print(matriz.nbytes)

56


Mostrar el elemento de la fila 2, columna 5

In [43]:
print(matriz[1, 5])  # Elemento en la fila 2, columna 3 (índices comienzan en 0)

14


Usar el arreglo con valores numéricos del 0 al 9.
Para ese arreglo, mostrar los elementos pares, comenzando desde la posición inicial.

In [50]:
print(arreglo_valores[::2])

[0 2 4 6 8]


# Pandas
Importar la librería Pandas, con el alias pd

In [3]:
import pandas as pd
import numpy as np

Crear un arreglo con valores numéricos del 0 al 9. Mostrar el contenido del arreglo.

In [6]:
arreglo = np.random.randint(10, size=(10),dtype=int)
print(arreglo)


[4 2 9 4 2 3 8 2 1 9]


Dado el siguiente set de datos:

Columnas = "A", "B" y "C"
Valores para cada columna = [1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [1, 8 , 6 ,7 ,6]

Organizarlos en un data frame Pandas.

In [7]:
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50], 'C': [1, 8 , 6 ,7 ,6]}
df = pd.DataFrame(data)
print(df)

   A   B  C
0  1  10  1
1  2  20  8
2  3  30  6
3  4  40  7
4  5  50  6


Mostrar el data frame Pandas creado en el paso anterior.

In [9]:
print(df)

   A   B  C
0  1  10  1
1  2  20  8
2  3  30  6
3  4  40  7
4  5  50  6


Enumerar las columnas del data frame.

In [12]:
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')


Enumerar los índices del data frame.

In [11]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)


Mostrar los valores de todas las columnas, para la fila 1, como arreglo.

In [14]:
print(df.iloc[0].values)  # Mostrar la primera fila

[ 1 10  1]


Mostrar los valores de todas las columnas, para la fila 2, como arreglo Pandas.

In [15]:
print(df.iloc[0]) 

A     1
B    10
C     1
Name: 0, dtype: int64


Mostrar la columna "B", y los índices menores que 3.

In [16]:
print(df.loc[df.index<3, "B"])

0    10
1    20
2    30
Name: B, dtype: int64


Re-escribir el filtro, anidando en un sólo bloque.

In [17]:
print(df[df.index < 3]["B"])

0    10
1    20
2    30
Name: B, dtype: int64


Trasponer el data frame.

In [ ]:
dfT = df.T
print(dfT)

    0   1   2   3   4
A   1   2   3   4   5
B  10  20  30  40  50
C   1   8   6   7   6


Obtener un dataframe, a partir de la suma de las columnas A y B del dataframe anterior.

In [ ]:
# Crear un nuevo DataFrame con la suma de las columnas A y B
df_suma = pd.DataFrame({'A+B': df['A'] + df['B']})
print(df_suma)

   A+B
0   11
1   22
2   33
3   44
4   55


Crear y asignar valores:

1 arreglo) Numeros_3 = range(51,70,2)

2 arreglo) Numeros_4 = range(1,15,3)

Usar esos arreglos para crear las correspondientes Series de Pandas.

In [ ]:
Numeros_3 = range(51,70,2)
Numeros_4 = range(1,15,3)

serie_3 = pd.Series(Numeros_3)
serie_4 = pd.Series(Numeros_4)
print(serie_3)
print(serie_4)



0    51
1    53
2    55
3    57
4    59
5    61
6    63
7    65
8    67
9    69
dtype: int64
0     1
1     4
2     7
3    10
4    13
dtype: int64


Crear una serie llamada "numeros_nan", resultado de multiplicar las 2 series creadas en el ejercicio anterior.

In [ ]:
numeros_nan = pd.Series(serie_3.multiply(serie_4))
print(numeros_nan)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
dtype: float64


Multiplicar un numpy.nan * otro número cualquiera

In [ ]:
resultado = np.nan * 5
print(resultado)  # El resultado será nan

nan


Sumar un numpy.nan * otro número cualquiera

In [ ]:
suma = np.nan + 5
print(suma)  # El resultado será nan

nan


Multiplicar varios números enteros, usando el método nanprod. Ver qué pasa si uno de esos valores enteros se reemplaza por np.nan

In [25]:
valores = [2, 3, 4]
producto = np.nanprod(valores)
print(producto)  # Resultado: 24

# Reemplazar uno de los valores por np.nan
valores_con_nan = [2, np.nan, 4]
producto_nan = np.nanprod(valores_con_nan)
print(producto_nan)  # Resultado: 8 (ignora el nan)

24
8.0


Sumar varios números enteros, usando el método nanprod. Ver qué pasa si uno de esos valores enteros se reemplaza por np.nan

In [26]:
valores = [2, 3, 4]
suma = np.nansum(valores)
print(suma)  # Resultado: 9

# Reemplazar uno de los valores por np.nan
valores_con_nan = [2, np.nan, 4]
suma_nan = np.nansum(valores_con_nan)
print(suma_nan)  # Resultado: 6 (ignora el nan)

9
6.0


verificar qué valor es null en el data frame numeros_nan

In [27]:
# Verificar qué valor es null en el data frame numeros_nan
print(numeros_nan.isnull())

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
9     True
dtype: bool


Con el método fillna, reemplazar los valores vacíos por el entero 23.

In [28]:
# Reemplazar los valores vacíos (NaN) por el entero 23 usando fillna
numeros_nan_lleno = numeros_nan.fillna(23)
print(numeros_nan_lleno)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
5     23.0
6     23.0
7     23.0
8     23.0
9     23.0
dtype: float64


Usar el método dropna para eliminar los valores vacíos del data frame numeros_nan

In [29]:
numeros_nan_vacios = numeros_nan.dropna()
print(numeros_nan_vacios)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
dtype: float64
